### ISSUE TITLE
unexpected token `"telegram_export"

### ISSUE THREAD

**Issue by codenoid** [expectocode/telegram-export#75] opened 2018-08-02 09:18 UTC
```
lele@lele-terbang:~$ telegram-export
# the mouse cursor is changed
/home/lele/.local/bin/telegram-export: line 2: syntax error near unexpected token `"telegram_export",'
/home/lele/.local/bin/telegram-export: line 2: `runpy.run_module("telegram_export", run_name="__main__", alter_sys=True)'
```
Spec : 
```
Python3
pip3 
install with both sudo and --user
```

**Comment by expectocode** [comment] 2018-08-02 11:26
thanks for the details, this seems to be a duplicate of #70

**Closed** 2018-08-02 11:26 UTC
